### ISSUE TITLE
wrap with abbreviation

### ISSUE THREAD

**Issue by ildarkhasanshin** [CudaText-addons/cuda_emmet#2]
```test```

1
wrap with abbreviation -> p
```
<p>
    test
</p>
```

2
wrap with abbreviation -> p*
```<p>test</p>```

в st4
wrap with abbreviation -> p == wrap with abbreviation -> p*
```<p>test</p>```

**Comment by Alexey-T** [comment]
that fact that ST4 allows `p*` is nothing. Cud has it's own Pascal-code Emmet. which handles incorrect case `p*` differently.

but.
you can still report this as an issue to the original repo!
here
https://github.com/rickard67/Emmet-Pascal

if author will fix it, I will get the fix.

**Comment by ildarkhasanshin** [comment]
https://github.com/rickard67/Emmet-Pascal/issues/12#issuecomment-1850909241

**Comment by CudaText-addons** [comment]
solved in that repo.
